import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import MainLayout from '@/components/MainLayout';
import './globals.css';

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Main | NextJs',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
